config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :venues
  get 'search_venues', to: "venues#search"
  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :venue
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ActiveRecord::Base
	has_many :events
	
	validates :owner, presence: true,
	length:{minimum: 5, maximum: 15}

	validates_uniqueness_of :name, scope: [:address]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:index]
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end

	def new
		
	end

	def create

	end

	def show

	end

	def edit
	
	end

	def update

	end
	
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

	before_action :set_venue, only: [:show, :edit, :destroy, :update]

	def index
		@venues = Venue.all
	end

	def new
		@venue = Venue.new
	end

	def create
		@venue = Venue.new(venue_params)
		if @venue.save
			flash[:success] = "Venue Created"
			redirect_to venues_path
		else
			render 'new'
		end
	end

	def search

	end

	def show

	end

	def edit

	end

	def destroy

	end


	def update

	end

	private

	def set_venue
		@venue = Venue.find(params[:id])
	end

	def venue_params
		params.require(:venue).permit(:name, :owner, :address)
	end

	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def maps

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class= "panel-heading">
				<h2 class= "panel-title">
					<%= pluralize(obj.errors.count, "error") %>
					occured while processing your request:
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<%end%>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<%end%>

app/views/events/index.html.erb
<h1> Events </h1>

<table>
	<thead>
		<th> Title </th>
		<th> Hosted By: </th>
		<th> Start Date </th>
		<th> Start Time </th>
		<th> End Date </th>
		<th> End Time </th>
	</thead>
		<% @events.each do |event| %>
			<tbody>
				<td><%= event.title %></td>
				<td><%= event.venue.name %></td>
				<td><%= "#{event.start_time.year}/#{event.start_time.month}/#{event.start_time.day}" %></td>
				<td><%= "#{event.start_time.hour}:#{event.start_time.min}" %></td>
				<td><%= "#{event.end_time.year}/#{event.end_time.month}/#{event.end_time.day}" %></td>
				<td><%= "#{event.end_time.hour}:#{event.end_time.min}" %></td>
			</tbody>
		<% end %>
</table>

<style>
	th {
		padding-right: 80px;
	}
</style>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="#">ProjSirens</a>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Link1", "/path1"  %></li>
      <li><%= link_to "Link2", "/path2"  %></li>
      <li><%= link_to "Link3", "/path3"  %></li>
    </ul>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjSirens" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->

  </head>
  <body>

    <%= render 'layouts/navigation' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
        </div><!--/span-->
      </div><!--/row-->    

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->
  </body>
</html>

app/views/venues/_lookup.html.erb
<div class="col-md-6 col-md-offset-4">
  <div id="floating-panel">
    <input id="address" type="textbox" value="Boston, MA, USA">
    <input id="submit" type="button" value="Geocode">
  </div>
</div>
<div class="col-md-6 col-md-offset-4" id="map"></div>
<br><br>
<table class="col-md-12 col-md-offset-2 table table-hover" id="venueList">
  <thead>
    <tr>
      <th> Venue Name </th>
      <th> Address </th>
    <tr>
  </thead>
  <tbody>
  </tbody>
</table>

<script>
  var map;
  var infowindow;

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: {lat: 42.3510, lng: -71.1310}
    });
    var geocoder = new google.maps.Geocoder();

    document.getElementById('submit').addEventListener('click', function() {
      geocodeAddress(geocoder, map);
    });
  }

  function callback(results, status) {
    $('#venueList tr').remove();
    if (status === google.maps.places.PlacesServiceStatus.OK) {
      for (var i = 0; i < results.length; i++) {
        createMarker(results[i]);
        //console.log(results[i]);
       $('#venueList').append('<tr><td>'+results[i].name+'</td>'+'<td>'+results[i].vicinity+'</td></tr>');
      }
    }
  }

  function createMarker(place) {
    var placeLoc = place.geometry.location;
    var marker = new google.maps.Marker({
      map: map,
      position: place.geometry.location
    });
    infowindow = new google.maps.InfoWindow();
    google.maps.event.addListener(marker, 'click', function() {
        infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + place.vicinity + '</div>');
        infowindow.open(map, this);
      });
  }

  function geocodeAddress(geocoder, resultsMap) {
    var address = document.getElementById('address').value;
    geocoder.geocode({'address': address}, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
        resultsMap.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: resultsMap,
          position: results[0].geometry.location
        });
        var request = {
          lat: results[0].geometry.location.lat(),
          lng: results[0].geometry.location.lng()
        };
        var service = new google.maps.places.PlacesService(map);
      service.nearbySearch({
        location: request,
        radius: 1000,
        type: ['night_club']
      }, callback);
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }
</script>

<script
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2SYDVuCiARIaztWQzXRmxhnusjvFeYZ0&libraries=places&callback=initMap" async defer>
</script>

app/views/venues/index.html.slim
h1 Venues

table.table.col-md-12
	thead
		tr
			th Venue
			th Owner
			th Address
	tbody
		-@venues.each do |venue|
			tr
				td = venue.name
				td = venue.owner
				td = venue.address

=link_to("New Venue", new_venue_path)

app/views/venues/new.html.erb
<%= render 'common/errors', obj: @venue %>
<div class="col-md-6 col-md-offset-4">
  <div id="floating-panel">
    <input id="address" type="textbox" value="Boston, MA, USA">
    <input id="submit" type="button" value="Geocode">
  </div>
</div>
<div class="col-md-6 col-md-offset-4" id="map"></div>
<br><br>
<table class="col-md-12 col-md-offset-2 table table-hover" id="venueList">
  <thead>
    <tr>
      <th> Venue Name </th>
      <th> Address </th>
    <tr>
  </thead>
  <tbody>
  </tbody>
</table>

<%= form_for(@venue, :html => {class: "form-horizontal", role: "form"}) do |f| %>
	<div class="form-group">
		<div class="col-sm-8">
			<%= f.text_field :name, class: "form-control", placeholder: "Venue Name", autofocus: true, readonly: true %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-8">
			<%= f.text_field :owner, class: "form-control", placeholder: "Owner", autofocus: true %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-8">
			<%= f.text_field :address, class: "form-control", placeholder: "Venue Address", autofocus: true, readonly: true %>
		</div>
	</div>
	<div class= 'form-group'>
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: 'btn btn-primary btn-lg'%>
		</div>
	</div>
<% end %>


<script>
  var map;
  var infowindow;

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: {lat: 42.3510, lng: -71.1310}
    });
    var geocoder = new google.maps.Geocoder();

    document.getElementById('submit').addEventListener('click', function() {
      geocodeAddress(geocoder, map);
    });
  }

  function callback(results, status) {
    $('#venueList tr').remove();
    if (status === google.maps.places.PlacesServiceStatus.OK) {
      for (var i = 0; i < results.length; i++) {
        createMarker(results[i]);
        //console.log(results[i]);
       $('#venueList').append('<tr><td>'+results[i].name+'</td>'+'<td>'+results[i].vicinity+'</td></tr>');
    
      }
    }
  }

  function createMarker(place) {
    var placeLoc = place.geometry.location;
    var marker = new google.maps.Marker({
      map: map,
      position: place.geometry.location
    });
    infowindow = new google.maps.InfoWindow();
    google.maps.event.addListener(marker, 'click', function() {
        infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + place.vicinity + '</div>');
        infowindow.open(map, this);
      });
  }

  function geocodeAddress(geocoder, resultsMap) {
    var address = document.getElementById('address').value;
    geocoder.geocode({'address': address}, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
        resultsMap.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: resultsMap,
          position: results[0].geometry.location
        });
        var request = {
          lat: results[0].geometry.location.lat(),
          lng: results[0].geometry.location.lng()
        };
        var service = new google.maps.places.PlacesService(map);
      service.nearbySearch({
        location: request,
        radius: 1000,
        type: ['night_club']
      }, callback);
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }
</script>

<script
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2SYDVuCiARIaztWQzXRmxhnusjvFeYZ0&libraries=places&callback=initMap" async defer>
</script>

<script>
$("#venueList").on('click','tr',function(e){
    e.preventDefault();
     var trValue = $(this).text();
     var tdValue = $(this).children('td').map(function (index, val) {
            return $(this).text();
        }).toArray();
        // all td value with comma seprated
    //alert(tdValue);
    //alert(trValue);
    $('#venue_name').val(tdValue[0]);
    $('#venue_address').val(tdValue[1]);
}); 

</script>
<!--
<br>

-->

app/views/welcome/index.html.erb
<h1> Welcome to the App </h1>
<%= link_to "logout", destroy_user_session_path, method: :delete %>
<%= link_to "Map", maps_path %>
    

app/views/welcome/maps.html.erb
<div id="floating-panel">
  <input id="address" type="textbox" value="Boston, MA, USA">
  <input id="submit" type="button" value="Geocode">
</div>
<div id="map"></div>
<script>
  var map;
  var infowindow;

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: {lat: 42.3510, lng: -71.1310}
    });
    var geocoder = new google.maps.Geocoder();

    document.getElementById('submit').addEventListener('click', function() {
      geocodeAddress(geocoder, map);
    });
  }

  function callback(results, status) {
    if (status === google.maps.places.PlacesServiceStatus.OK) {
      for (var i = 0; i < results.length; i++) {
        createMarker(results[i]);
        console.log(results[i]);
      }
    }
  }

  function createMarker(place) {
    var placeLoc = place.geometry.location;
    var marker = new google.maps.Marker({
      map: map,
      position: place.geometry.location
    });
    infowindow = new google.maps.InfoWindow();
    google.maps.event.addListener(marker, 'click', function() {
        infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + place.vicinity + '</div>');
        infowindow.open(map, this);
      });
  }

  function geocodeAddress(geocoder, resultsMap) {
    var address = document.getElementById('address').value;
    geocoder.geocode({'address': address}, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
        resultsMap.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: resultsMap,
          position: results[0].geometry.location
        });
        var request = {
          lat: results[0].geometry.location.lat(),
          lng: results[0].geometry.location.lng()
        };
        var service = new google.maps.places.PlacesService(map);
      service.nearbySearch({
        location: request,
        radius: 500,
        type: ['night_club']
      }, callback);
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }
</script>

<script
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2SYDVuCiARIaztWQzXRmxhnusjvFeYZ0&libraries=places&callback=initMap" async defer>
</script>